language: java
sudo: false

jdk:
  - oraclejdk8

before_install:
  - git clone --depth=50 --branch=master git://github.com/Garrit/java-common.git /home/travis/build/Garrit/java-common
  - cd /home/travis/build/Garrit/java-common
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B
  - cd /home/travis/build/Garrit/judge