name: judge-00
negotiator: http://negotiator:7165
problems: /path/to/problem/definitions

server:
  applicationConnectors:
  - type: http
    port: 7167
  adminConnectors:
  - type: http
    port: 7177
